import { CustomQuestionResponse } from "@/types/responses/custom.question.response";

/**
 * MOCK: hàng đợi kiểm duyệt prompt (câu hỏi tuỳ chỉnh) do học viên đóng góp.
 * Seed cho localStorage store. Thay bằng API thật khi BE sẵn sàng.
 */
export const MOCK_CUSTOM_QUESTIONS: CustomQuestionResponse[] = [
    {
        id: "mq-1",
        submitterName: "Nguyễn Minh Tuấn",
        submitterEmail: "tuannm.brse@fpt.edu.vn",
        submitterUserId: "u-learner-001",
        submittedAt: "2026-06-12T09:15:00.000Z",
        japaneseQuestion: "御社の開発チームの規模について教えていただけますか？",
        japaneseQuestionMarkup:
            "おんしゃのかいはつチームのきぼについておしえていただけますか？",
        contextualHint:
            "Em đang chuẩn bị phỏng vấn vị trí BrSE Junior cho một công ty Nhật, muốn hỏi lịch sự về quy mô team dev.",
        topicId: "",
        vocabularies: [
            {
                id: "v-1",
                japaneseWord: "御社",
                furiganaMarkup: "おんしゃ",
                vietnameseMeaning: "Quý công ty (kính ngữ)",
                englishMeaning: "Your company (honorific)",
            },
            {
                id: "v-2",
                japaneseWord: "開発チーム",
                furiganaMarkup: "かいはつチーム",
                vietnameseMeaning: "Đội phát triển",
                englishMeaning: "Development team",
            },
            {
                id: "v-3",
                japaneseWord: "規模",
                furiganaMarkup: "きぼ",
                vietnameseMeaning: "Quy mô",
                englishMeaning: "Scale",
            },
        ],
        grammars: [
            {
                id: "g-1",
                japanesePattern: "〜について教えていただけますか",
                furiganaMarkup: "〜についておしえていただけますか",
                vietnameseMeaning: "Anh/chị có thể cho tôi biết về ~ không ạ?",
                englishMeaning: "Could you please tell me about ~?",
                explanation:
                    "Mẫu yêu cầu lịch sự dùng 〜ていただけますか kết hợp với 教える ở dạng khiêm nhường.",
            },
        ],
        status: "PENDING",
        rejectionCategory: "",
        rejectionReason: "",
        reviewedAt: "",
    },
    {
        id: "mq-2",
        submitterName: "Trần Thị Thanh An",
        submitterEmail: "antt.dev@gmail.com",
        submitterUserId: "u-learner-002",
        submittedAt: "2026-06-12T03:40:00.000Z",
        japaneseQuestion: "週末によく行くカフェを紹介してください。",
        japaneseQuestionMarkup:
            "しゅうまつによくいくカフェをしょうかいしてください。",
        contextualHint: "Luyện phản xạ chủ đề đời sống hằng ngày, mức độ N4.",
        topicId: "",
        vocabularies: [
            {
                id: "v-4",
                japaneseWord: "週末",
                furiganaMarkup: "しゅうまつ",
                vietnameseMeaning: "Cuối tuần",
                englishMeaning: "Weekend",
            },
            {
                id: "v-5",
                japaneseWord: "紹介する",
                furiganaMarkup: "しょうかいする",
                vietnameseMeaning: "Giới thiệu",
                englishMeaning: "To introduce",
            },
        ],
        grammars: [
            {
                id: "g-2",
                japanesePattern: "〜てください",
                furiganaMarkup: "〜てください",
                vietnameseMeaning: "Hãy ~ giúp tôi",
                englishMeaning: "Please do ~",
                explanation: "Mẫu yêu cầu/đề nghị lịch sự cơ bản trình độ N5–N4.",
            },
        ],
        status: "PENDING",
        rejectionCategory: "",
        rejectionReason: "",
        reviewedAt: "",
    },
    {
        id: "mq-3",
        submitterName: "Lê Hoàng Phúc",
        submitterEmail: "phuclh.it@fpt.edu.vn",
        submitterUserId: "u-learner-003",
        submittedAt: "2026-06-11T07:05:00.000Z",
        japaneseQuestion: "デイリースタンドアップで進捗を簡潔に報告してください。",
        japaneseQuestionMarkup:
            "デイリースタンドアップでしんちょくをかんけつにほうこくしてください。",
        contextualHint:
            "Tình huống IT công sở — luyện báo cáo nhanh trong daily meeting.",
        topicId: "",
        vocabularies: [
            {
                id: "v-6",
                japaneseWord: "進捗",
                furiganaMarkup: "しんちょく",
                vietnameseMeaning: "Tiến độ",
                englishMeaning: "Progress",
            },
            {
                id: "v-7",
                japaneseWord: "報告する",
                furiganaMarkup: "ほうこくする",
                vietnameseMeaning: "Báo cáo",
                englishMeaning: "To report",
            },
        ],
        grammars: [],
        status: "PENDING",
        rejectionCategory: "",
        rejectionReason: "",
        reviewedAt: "",
    },
    {
        id: "mq-4",
        submitterName: "Phạm Quốc Đạt",
        submitterEmail: "datpq.brse@fpt.edu.vn",
        submitterUserId: "u-learner-004",
        submittedAt: "2026-06-10T02:20:00.000Z",
        japaneseQuestion: "本番環境で発生したバグの原因を上司に報告してください。",
        japaneseQuestionMarkup:
            "ほんばんかんきょうではっせいしたバグのげんいんをじょうしにほうこくしてください。",
        contextualHint: "Báo cáo sự cố production cho leader — yêu cầu sử dụng Keigo.",
        topicId: "t-3",
        vocabularies: [
            {
                id: "v-8",
                japaneseWord: "本番環境",
                furiganaMarkup: "ほんばんかんきょう",
                vietnameseMeaning: "Môi trường production",
                englishMeaning: "Production environment",
            },
            {
                id: "v-9",
                japaneseWord: "原因",
                furiganaMarkup: "げんいん",
                vietnameseMeaning: "Nguyên nhân",
                englishMeaning: "Cause",
            },
        ],
        grammars: [],
        status: "APPROVED",
        rejectionCategory: "",
        rejectionReason: "",
        reviewedAt: "2026-06-10T08:00:00.000Z",
    },
    {
        id: "mq-5",
        submitterName: "Vũ Thị Mai",
        submitterEmail: "maivt.dev@gmail.com",
        submitterUserId: "u-learner-005",
        submittedAt: "2026-06-09T06:30:00.000Z",
        japaneseQuestion: "コードレビューで指摘された点を丁寧に確認してください。",
        japaneseQuestionMarkup:
            "コードレビューでしてきされたてんをていねいにかくにんしてください。",
        contextualHint: "Tình huống IT — phản hồi reviewer trên Pull Request.",
        topicId: "t-3",
        vocabularies: [
            {
                id: "v-10",
                japaneseWord: "指摘する",
                furiganaMarkup: "してきする",
                vietnameseMeaning: "Chỉ ra, góp ý",
                englishMeaning: "To point out",
            },
        ],
        grammars: [],
        status: "APPROVED",
        rejectionCategory: "",
        rejectionReason: "",
        reviewedAt: "2026-06-09T10:15:00.000Z",
    },
    {
        id: "mq-6",
        submitterName: "Đỗ Anh Tuấn",
        submitterEmail: "tuanda.brse@fpt.edu.vn",
        submitterUserId: "u-learner-006",
        submittedAt: "2026-06-08T08:45:00.000Z",
        japaneseQuestion: "リリース延期について顧客に謝罪のメールを口頭で説明してください。",
        japaneseQuestionMarkup:
            "リリースえんきについてこきゃくにしゃざいのメールをこうとうでせつめいしてください。",
        contextualHint: "Tình huống xin lỗi khách hàng — mức độ kính ngữ cao.",
        topicId: "",
        vocabularies: [
            {
                id: "v-11",
                japaneseWord: "延期",
                furiganaMarkup: "えんき",
                vietnameseMeaning: "Hoãn lại",
                englishMeaning: "Postponement",
            },
            {
                id: "v-12",
                japaneseWord: "謝罪",
                furiganaMarkup: "しゃざい",
                vietnameseMeaning: "Lời xin lỗi",
                englishMeaning: "Apology",
            },
        ],
        grammars: [],
        status: "PENDING",
        rejectionCategory: "",
        rejectionReason: "",
        reviewedAt: "",
    },
    {
        id: "mq-7",
        submitterName: "Hoàng Văn Sơn",
        submitterEmail: "sonhv.dev@gmail.com",
        submitterUserId: "u-learner-007",
        submittedAt: "2026-06-07T11:10:00.000Z",
        japaneseQuestion: "好きなアニメについて自由に話してください。",
        japaneseQuestionMarkup: "すきなアニメについてじゆうにはなしてください。",
        contextualHint: "Chủ đề giải trí cá nhân.",
        topicId: "",
        vocabularies: [],
        grammars: [],
        status: "REJECTED",
        rejectionCategory: "OFF_TOPIC",
        rejectionReason:
            "Nội dung quá chung chung và không gắn với mục tiêu giao tiếp công sở/phỏng vấn của khoá học. Đề nghị bổ sung ngữ cảnh cụ thể hơn.",
        reviewedAt: "2026-06-07T14:00:00.000Z",
    },
    {
        id: "mq-8",
        submitterName: "Bùi Thu Hằng",
        submitterEmail: "hangbt.brse@fpt.edu.vn",
        submitterUserId: "u-learner-008",
        submittedAt: "2026-06-06T01:25:00.000Z",
        japaneseQuestion: "上司に有給休暇を申請するときの言い回しを練習してください。",
        japaneseQuestionMarkup:
            "じょうしにゆうきゅうきゅうかをしんせいするときのいいまわしをれんしゅうしてください。",
        contextualHint: "Giao tiếp công sở — đề nghị nghỉ phép.",
        topicId: "t-3",
        vocabularies: [
            {
                id: "v-13",
                japaneseWord: "有給休暇",
                furiganaMarkup: "ゆうきゅうきゅうか",
                vietnameseMeaning: "Nghỉ phép có lương",
                englishMeaning: "Paid leave",
            },
            {
                id: "v-14",
                japaneseWord: "申請する",
                furiganaMarkup: "しんせいする",
                vietnameseMeaning: "Đề nghị, xin (thủ tục)",
                englishMeaning: "To apply / request",
            },
        ],
        grammars: [],
        status: "APPROVED",
        rejectionCategory: "",
        rejectionReason: "",
        reviewedAt: "2026-06-06T09:30:00.000Z",
    },
    {
        id: "mq-9",
        submitterName: "Ngô Minh Quân",
        submitterEmail: "quannm.it@fpt.edu.vn",
        submitterUserId: "u-learner-009",
        submittedAt: "2026-06-05T04:50:00.000Z",
        japaneseQuestion: "会議に遅れる際の連絡方法を説明してください。",
        japaneseQuestionMarkup:
            "かいぎにおくれるさいのれんらくほうほうをせつめいしてください。",
        contextualHint: "Tình huống công sở — thông báo đến trễ cuộc họp.",
        topicId: "",
        vocabularies: [
            {
                id: "v-15",
                japaneseWord: "連絡",
                furiganaMarkup: "れんらく",
                vietnameseMeaning: "Liên lạc",
                englishMeaning: "Contact",
            },
        ],
        grammars: [
            {
                id: "g-3",
                japanesePattern: "〜際に",
                furiganaMarkup: "〜さいに",
                vietnameseMeaning: "Khi/lúc ~ (trang trọng)",
                englishMeaning: "When ~ (formal)",
                explanation: "〜際に là cách nói trang trọng của 〜とき, thường dùng văn viết/công sở.",
            },
        ],
        status: "PENDING",
        rejectionCategory: "",
        rejectionReason: "",
        reviewedAt: "",
    },
];
