import { TopicDetailResponse } from "@/types/responses/topic.response";

export const MOCK_TOPICS: TopicDetailResponse[] = [
    {
        id: "t-office-it",
        name: "Giao tiếp văn phòng IT",
        jlptLevel: "N3",
        description:
            "Luyện các mẫu hội thoại thường gặp tại công ty IT Nhật: chào hỏi đầu ngày, trao đổi tiến độ, xin nghỉ phép, báo cáo sự cố.",
        questionCount: 5,
        averageScore: 8.2,
        status: "ACTIVE",
        orderIndex: 1,
        questions: [
            {
                id: "q1",
                jp: "おはようございます。",
                furigana: "おはようございます。",
                vi: "Hãy chào buổi sáng với sếp.",
                vocab: [
                    { jp: "おはようございます", furigana: "おはようございます", vi: "Chào buổi sáng (lịch sự)" },
                    { jp: "今日も", furigana: "きょうも", vi: "Hôm nay cũng…" },
                    { jp: "よろしくお願いいたします", furigana: "よろしくおねがいいたします", vi: "Mong được giúp đỡ" },
                ],
                sentences: [
                    { jp: "〜もよろしくお願いいたします。", vi: "Mẫu chào lịch sự đầu ngày." },
                    { jp: "本日は〜です。", vi: "Hôm nay là …" },
                ],
                contextHintJp: "IT会社の朝、上司に挨拶する場面です。",
                contextHintVi: "Buổi sáng tại công ty IT, chào hỏi cấp trên một cách lịch sự.",
            },
            {
                id: "q2",
                jp: "今日のタスクの進捗を報告してください。",
                furigana: "きょうのタスクのしんちょくをほうこくしてください。",
                vi: "Báo cáo tiến độ task hôm nay.",
                vocab: [
                    { jp: "進捗", furigana: "しんちょく", vi: "Tiến độ" },
                    { jp: "完了", furigana: "かんりょう", vi: "Hoàn thành" },
                    { jp: "リリース", furigana: "リリース", vi: "Release" },
                ],
                sentences: [
                    { jp: "現在、〜は〇〇%完了しております。", vi: "Báo cáo tiến độ phần trăm." },
                    { jp: "明日中に〜可能です。", vi: "Có thể … trong ngày mai." },
                ],
                contextHintJp: "朝会で、担当タスクの進捗を簡潔に共有します。",
                contextHintVi: "Trong họp standup, chia sẻ ngắn gọn tiến độ task phụ trách.",
            },
            {
                id: "q3",
                jp: "明日休みを取らせていただきたいです。",
                furigana: "あしたやすみをとらせていただきたいです。",
                vi: "Xin nghỉ phép vào ngày mai.",
                vocab: [
                    { jp: "休み", furigana: "やすみ", vi: "Nghỉ phép" },
                    { jp: "体調不良", furigana: "たいちょうふりょう", vi: "Sức khoẻ không tốt" },
                    { jp: "申し訳ございません", furigana: "もうしわけございません", vi: "Xin lỗi (rất kính ngữ)" },
                ],
                sentences: [
                    { jp: "申し訳ございませんが、〜たいです。", vi: "Xin lỗi và đề nghị điều gì đó." },
                    { jp: "〜のため、お休みをいただきたいです。", vi: "Vì lý do… xin được nghỉ." },
                ],
                contextHintJp: "上司に丁寧に休暇を申請する場面です。",
                contextHintVi: "Xin phép nghỉ với cấp trên một cách lịch sự.",
            },
            {
                id: "q4",
                jp: "緊急のバグが発生しました。",
                furigana: "きんきゅうのバグがはっせいしました。",
                vi: "Báo sếp về một bug khẩn cấp.",
                vocab: [
                    { jp: "緊急", furigana: "きんきゅう", vi: "Khẩn cấp" },
                    { jp: "本番環境", furigana: "ほんばんかんきょう", vi: "Môi trường production" },
                    { jp: "対応", furigana: "たいおう", vi: "Xử lý / ứng phó" },
                ],
                sentences: [
                    { jp: "〜で緊急のバグが発生しました。", vi: "Báo có bug khẩn cấp ở …" },
                    { jp: "今すぐ対応いたします。", vi: "Em sẽ xử lý ngay." },
                ],
                contextHintJp: "本番環境のトラブルを上司へ素早く報告します。",
                contextHintVi: "Báo nhanh sự cố production cho cấp trên.",
            },
            {
                id: "q5",
                jp: "手伝ってくださってありがとうございます。",
                furigana: "てつだってくださってありがとうございます。",
                vi: "Cảm ơn đồng nghiệp đã giúp đỡ.",
                vocab: [
                    { jp: "手伝う", furigana: "てつだう", vi: "Giúp đỡ" },
                    { jp: "本当に", furigana: "ほんとうに", vi: "Thật sự" },
                    { jp: "助かりました", furigana: "たすかりました", vi: "Đã được giúp đỡ" },
                ],
                sentences: [
                    { jp: "先ほどは〜くださって、ありがとうございました。", vi: "Cảm ơn vì việc vừa rồi." },
                    { jp: "おかげさまで〜できました。", vi: "Nhờ có anh/chị mà em đã…" },
                ],
                contextHintJp: "助けてくれた同僚へ感謝を伝える場面です。",
                contextHintVi: "Cảm ơn đồng nghiệp đã hỗ trợ mình.",
            },
        ],
    },
    {
        id: "t-daily-standup",
        name: "Họp Daily Standup",
        jlptLevel: "N3",
        description:
            "Mô phỏng buổi họp standup buổi sáng: nói về việc hôm qua đã làm, hôm nay sẽ làm, và các vấn đề đang gặp.",
        questionCount: 4,
        averageScore: 7.8,
        status: "ACTIVE",
        orderIndex: 2,
        questions: [
            {
                id: "q1",
                jp: "昨日は何をしましたか？",
                furigana: "きのうはなにをしましたか？",
                vi: "Hôm qua bạn đã làm gì?",
                vocab: [
                    { jp: "昨日", furigana: "きのう", vi: "Hôm qua" },
                    { jp: "テスト", furigana: "テスト", vi: "Kiểm thử" },
                    { jp: "バグ修正", furigana: "バグしゅうせい", vi: "Sửa bug" },
                ],
                sentences: [
                    { jp: "昨日は〜を行いました。", vi: "Hôm qua tôi đã làm…" },
                    { jp: "〜と〜をしました。", vi: "Liệt kê 2 việc đã làm." },
                ],
                contextHintJp: "朝会で前日の作業内容を共有します。",
                contextHintVi: "Chia sẻ công việc hôm qua trong họp standup.",
            },
            {
                id: "q2",
                jp: "今日の予定は何ですか？",
                furigana: "きょうのよていはなんですか？",
                vi: "Hôm nay kế hoạch của bạn là gì?",
                vocab: [
                    { jp: "予定", furigana: "よてい", vi: "Kế hoạch" },
                    { jp: "リファクタリング", furigana: "リファクタリング", vi: "Refactor" },
                    { jp: "レビュー", furigana: "レビュー", vi: "Review code" },
                ],
                sentences: [
                    { jp: "今日は〜を予定しています。", vi: "Hôm nay tôi dự định …" },
                    { jp: "午後は〜に取り組みます。", vi: "Buổi chiều sẽ làm …" },
                ],
                contextHintJp: "本日の作業計画を簡潔に伝えます。",
                contextHintVi: "Trình bày kế hoạch công việc trong ngày.",
            },
            {
                id: "q3",
                jp: "何か問題はありますか？",
                furigana: "なにかもんだいはありますか？",
                vi: "Bạn có gặp vấn đề gì không?",
                vocab: [
                    { jp: "問題", furigana: "もんだい", vi: "Vấn đề" },
                    { jp: "相談", furigana: "そうだん", vi: "Trao đổi / xin ý kiến" },
                    { jp: "設計", furigana: "せっけい", vi: "Thiết kế" },
                ],
                sentences: [
                    { jp: "今のところ〜はありません。", vi: "Hiện chưa có …" },
                    { jp: "〜について相談したいです。", vi: "Em muốn trao đổi về …" },
                ],
                contextHintJp: "ブロッカーや相談したい点を共有します。",
                contextHintVi: "Chia sẻ blocker hoặc điểm cần trao đổi.",
            },
            {
                id: "q4",
                jp: "誰かのサポートが必要ですか？",
                furigana: "だれかのサポートがひつようですか？",
                vi: "Bạn cần ai hỗ trợ không?",
                vocab: [
                    { jp: "サポート", furigana: "サポート", vi: "Hỗ trợ" },
                    { jp: "必要", furigana: "ひつよう", vi: "Cần thiết" },
                    { jp: "お願いしたい", furigana: "おねがいしたい", vi: "Muốn nhờ" },
                ],
                sentences: [
                    { jp: "〜さんのサポートをお願いしたいです。", vi: "Muốn nhờ ai đó hỗ trợ." },
                    { jp: "〜周りで助けが必要です。", vi: "Cần giúp ở mảng …" },
                ],
                contextHintJp: "サポートが必要な点をチームに伝えます。",
                contextHintVi: "Nói rõ phần cần được hỗ trợ với team.",
            },
        ],
    },
    {
        id: "t-office-email",
        name: "Email công sở",
        jlptLevel: "N3",
        description:
            "Luyện đọc và diễn đạt các mẫu câu thường dùng khi viết và phản hồi email công sở.",
        questionCount: 3,
        averageScore: 7.5,
        status: "ACTIVE",
        orderIndex: 3,
        questions: [
            {
                id: "q1",
                jp: "メールを受け取りました。",
                furigana: "メールをうけとりました。",
                vi: "Xác nhận đã nhận email.",
                vocab: [
                    { jp: "受け取る", furigana: "うけとる", vi: "Nhận được" },
                    { jp: "確かに", furigana: "たしかに", vi: "Chắc chắn" },
                    { jp: "ご連絡", furigana: "ごれんらく", vi: "Liên hệ (kính ngữ)" },
                ],
                sentences: [
                    { jp: "ご連絡ありがとうございます。", vi: "Cảm ơn vì đã liên hệ." },
                    { jp: "メールを確かに受け取りました。", vi: "Đã nhận được email." },
                ],
                contextHintJp: "取引先からのメールに丁寧に返信します。",
                contextHintVi: "Phản hồi email của đối tác một cách lịch sự.",
            },
            {
                id: "q2",
                jp: "会議の時間を変更していただけますか？",
                furigana: "かいぎのじかんをへんこうしていただけますか？",
                vi: "Đề nghị dời lịch họp.",
                vocab: [
                    { jp: "会議", furigana: "かいぎ", vi: "Cuộc họp" },
                    { jp: "変更", furigana: "へんこう", vi: "Thay đổi" },
                    { jp: "恐れ入りますが", furigana: "おそれいりますが", vi: "Xin phép làm phiền" },
                ],
                sentences: [
                    { jp: "恐れ入りますが、〜していただけますか。", vi: "Lịch sự nhờ đổi/thay đổi gì đó." },
                    { jp: "〜時に変更していただけますでしょうか。", vi: "Đề nghị đổi sang giờ …" },
                ],
                contextHintJp: "会議のリスケジュールを丁寧に依頼します。",
                contextHintVi: "Đề nghị dời lịch họp một cách lịch sự.",
            },
            {
                id: "q3",
                jp: "よろしくお願いいたします。",
                furigana: "よろしくおねがいいたします。",
                vi: "Gửi lời cảm ơn cuối email.",
                vocab: [
                    { jp: "今後とも", furigana: "こんごとも", vi: "Từ nay về sau" },
                    { jp: "よろしく", furigana: "よろしく", vi: "Mong được tốt đẹp" },
                    { jp: "お願いいたします", furigana: "おねがいいたします", vi: "Xin nhờ (kính ngữ)" },
                ],
                sentences: [
                    { jp: "今後ともよろしくお願いいたします。", vi: "Mẫu kết email tiêu chuẩn." },
                    { jp: "引き続きよろしくお願いいたします。", vi: "Mong tiếp tục hợp tác." },
                ],
                contextHintJp: "ビジネスメールの結びの挨拶です。",
                contextHintVi: "Câu chào kết thúc email công việc.",
            },
        ],
    },
    {
        id: "t-travel-japan",
        name: "Đi du lịch Nhật Bản",
        jlptLevel: "N4",
        description:
            "Các tình huống giao tiếp khi du lịch: hỏi đường, đặt phòng, gọi món, mua sắm.",
        questionCount: 4,
        averageScore: 7.2,
        status: "ACTIVE",
        orderIndex: 4,
        questions: [
            {
                id: "q1",
                jp: "新宿駅はどこですか？",
                furigana: "しんじゅくえきはどこですか？",
                vi: "Hỏi đường đến ga Shinjuku.",
                vocab: [
                    { jp: "新宿駅", furigana: "しんじゅくえき", vi: "Ga Shinjuku" },
                    { jp: "道", furigana: "みち", vi: "Đường" },
                    { jp: "教える", furigana: "おしえる", vi: "Chỉ / dạy" },
                ],
                sentences: [
                    { jp: "すみません、〜までの道を教えていただけますか？", vi: "Hỏi đường lịch sự." },
                    { jp: "〜はどこですか？", vi: "… ở đâu vậy?" },
                ],
                contextHintJp: "道に迷ったとき、通行人に道を尋ねます。",
                contextHintVi: "Khi lạc đường, hỏi người đi đường chỉ giúp.",
            },
            {
                id: "q2",
                jp: "2泊の予約をお願いします。",
                furigana: "にはくのよやくをおねがいします。",
                vi: "Đặt phòng khách sạn cho 2 đêm.",
                vocab: [
                    { jp: "予約", furigana: "よやく", vi: "Đặt chỗ" },
                    { jp: "シングルルーム", furigana: "シングルルーム", vi: "Phòng đơn" },
                    { jp: "2泊", furigana: "にはく", vi: "2 đêm" },
                ],
                sentences: [
                    { jp: "〜で〇泊の予約をお願いしたいのですが。", vi: "Đặt phòng X đêm." },
                    { jp: "〜から〜まで泊まりたいです。", vi: "Muốn ở từ ngày … đến …" },
                ],
                contextHintJp: "ホテルのフロントで宿泊予約をします。",
                contextHintVi: "Đặt phòng tại quầy lễ tân khách sạn.",
            },
            {
                id: "q3",
                jp: "このラーメンはいくらですか？",
                furigana: "このラーメンはいくらですか？",
                vi: "Hỏi giá món ramen.",
                vocab: [
                    { jp: "ラーメン", furigana: "ラーメン", vi: "Mì ramen" },
                    { jp: "いくら", furigana: "いくら", vi: "Bao nhiêu tiền" },
                    { jp: "おいくら", furigana: "おいくら", vi: "Bao nhiêu (lịch sự)" },
                ],
                sentences: [
                    { jp: "この〜はおいくらですか？", vi: "Cái này giá bao nhiêu?" },
                    { jp: "一番安いのはどれですか？", vi: "Cái nào rẻ nhất?" },
                ],
                contextHintJp: "飲食店でメニューの値段を尋ねます。",
                contextHintVi: "Hỏi giá món trong quán ăn.",
            },
            {
                id: "q4",
                jp: "終電は何時ですか？",
                furigana: "しゅうでんはなんじですか？",
                vi: "Hỏi giờ tàu cuối cùng.",
                vocab: [
                    { jp: "終電", furigana: "しゅうでん", vi: "Tàu cuối" },
                    { jp: "何時", furigana: "なんじ", vi: "Mấy giờ" },
                    { jp: "行き", furigana: "ゆき", vi: "Đi tới…" },
                ],
                sentences: [
                    { jp: "〜行きの終電は何時ですか？", vi: "Tàu cuối đi … là mấy giờ?" },
                    { jp: "次の電車は何時ですか？", vi: "Chuyến tàu kế tiếp mấy giờ?" },
                ],
                contextHintJp: "駅員に終電の時刻を確認します。",
                contextHintVi: "Hỏi nhân viên nhà ga giờ tàu cuối.",
            },
        ],
    },
    {
        id: "t-daily-life",
        name: "Hội thoại hằng ngày",
        jlptLevel: "N4",
        description:
            "Luyện các đoạn hội thoại đơn giản với bạn bè, hàng xóm, đồng nghiệp trong cuộc sống hằng ngày.",
        questionCount: 5,
        averageScore: 8.6,
        status: "ACTIVE",
        orderIndex: 5,
        questions: [
            {
                id: "q1",
                jp: "はじめまして、よろしくお願いします。",
                furigana: "はじめまして、よろしくおねがいします。",
                vi: "Giới thiệu bản thân ngắn gọn.",
                vocab: [
                    { jp: "はじめまして", furigana: "はじめまして", vi: "Lần đầu gặp" },
                    { jp: "申します", furigana: "もうします", vi: "Tôi tên là (lịch sự)" },
                    { jp: "よろしく", furigana: "よろしく", vi: "Mong được làm quen" },
                ],
                sentences: [
                    { jp: "はじめまして、〜と申します。", vi: "Lần đầu gặp, tôi là …" },
                    { jp: "どうぞよろしくお願いします。", vi: "Rất mong được giúp đỡ." },
                ],
                contextHintJp: "初対面の相手に自己紹介をします。",
                contextHintVi: "Giới thiệu bản thân với người mới gặp.",
            },
            {
                id: "q2",
                jp: "週末は何をしますか？",
                furigana: "しゅうまつはなにをしますか？",
                vi: "Cuối tuần bạn thường làm gì?",
                vocab: [
                    { jp: "週末", furigana: "しゅうまつ", vi: "Cuối tuần" },
                    { jp: "カフェ", furigana: "カフェ", vi: "Quán cà phê" },
                    { jp: "出かける", furigana: "でかける", vi: "Đi ra ngoài" },
                ],
                sentences: [
                    { jp: "〜たり、〜たりします。", vi: "Liệt kê các việc thường làm." },
                    { jp: "よく〜に行きます。", vi: "Thường hay đi …" },
                ],
                contextHintJp: "友達と週末の予定について話します。",
                contextHintVi: "Trò chuyện với bạn bè về kế hoạch cuối tuần.",
            },
            {
                id: "q3",
                jp: "今晩、一緒に食事しませんか？",
                furigana: "こんばん、いっしょにしょくじしませんか？",
                vi: "Mời bạn đi ăn tối.",
                vocab: [
                    { jp: "今晩", furigana: "こんばん", vi: "Tối nay" },
                    { jp: "一緒に", furigana: "いっしょに", vi: "Cùng nhau" },
                    { jp: "夕食", furigana: "ゆうしょく", vi: "Bữa tối" },
                ],
                sentences: [
                    { jp: "もしよかったら、〜ませんか？", vi: "Nếu được thì cùng … nhé?" },
                    { jp: "一緒に〜しましょう。", vi: "Cùng nhau … nào." },
                ],
                contextHintJp: "友人を食事に誘います。",
                contextHintVi: "Rủ bạn cùng đi ăn.",
            },
            {
                id: "q4",
                jp: "お元気ですか？",
                furigana: "おげんきですか？",
                vi: "Hỏi thăm sức khỏe.",
                vocab: [
                    { jp: "お久しぶり", furigana: "おひさしぶり", vi: "Lâu rồi không gặp" },
                    { jp: "元気", furigana: "げんき", vi: "Khoẻ" },
                    { jp: "過ごす", furigana: "すごす", vi: "Trải qua" },
                ],
                sentences: [
                    { jp: "お久しぶりです。お元気ですか？", vi: "Lâu rồi không gặp, anh/chị khoẻ chứ?" },
                    { jp: "最近どうですか？", vi: "Dạo này thế nào?" },
                ],
                contextHintJp: "久しぶりに会った知人に挨拶します。",
                contextHintVi: "Chào hỏi người quen lâu ngày gặp lại.",
            },
            {
                id: "q5",
                jp: "プレゼントをありがとうございます。",
                furigana: "プレゼントをありがとうございます。",
                vi: "Cảm ơn vì món quà.",
                vocab: [
                    { jp: "プレゼント", furigana: "プレゼント", vi: "Quà tặng" },
                    { jp: "素敵", furigana: "すてき", vi: "Tuyệt vời" },
                    { jp: "本当に", furigana: "ほんとうに", vi: "Thật sự" },
                ],
                sentences: [
                    { jp: "素敵な〜を本当にありがとうございます。", vi: "Cảm ơn vì món … tuyệt vời." },
                    { jp: "とても気に入りました。", vi: "Tôi rất thích nó." },
                ],
                contextHintJp: "贈り物をもらったお礼を伝えます。",
                contextHintVi: "Nói lời cảm ơn khi nhận được quà.",
            },
        ],
    },
    {
        id: "t-brse-interview",
        name: "Phỏng vấn vị trí BrSE",
        jlptLevel: "N2",
        description:
            "Mô phỏng buổi phỏng vấn xin việc BrSE với nhà tuyển dụng Nhật: giới thiệu bản thân, kinh nghiệm dự án, lý do ứng tuyển.",
        questionCount: 6,
        averageScore: 7.9,
        status: "DRAFT",
        orderIndex: 6,
        questions: [
            {
                id: "q1",
                jp: "自己紹介をお願いします。",
                furigana: "じこしょうかいをおねがいします。",
                vi: "Hãy giới thiệu bản thân.",
                vocab: [
                    { jp: "自己紹介", furigana: "じこしょうかい", vi: "Giới thiệu bản thân" },
                    { jp: "専攻", furigana: "せんこう", vi: "Chuyên ngành" },
                    { jp: "大学", furigana: "だいがく", vi: "Đại học" },
                ],
                sentences: [
                    { jp: "はじめまして、〜と申します。", vi: "Mở đầu phỏng vấn." },
                    { jp: "〜大学の〜専攻〇年生です。", vi: "Giới thiệu trường và năm học." },
                ],
                contextHintJp: "面接の冒頭で自己紹介をします。",
                contextHintVi: "Giới thiệu bản thân ở đầu buổi phỏng vấn.",
            },
            {
                id: "q2",
                jp: "なぜBrSEになりたいですか？",
                furigana: "なぜBrSEになりたいですか？",
                vi: "Tại sao bạn muốn làm BrSE?",
                vocab: [
                    { jp: "技術", furigana: "ぎじゅつ", vi: "Kỹ thuật" },
                    { jp: "活かす", furigana: "いかす", vi: "Vận dụng" },
                    { jp: "橋", furigana: "はし", vi: "Cầu nối" },
                ],
                sentences: [
                    { jp: "〜を活かして、〜になりたいです。", vi: "Vận dụng … để trở thành …" },
                    { jp: "〜をつなぐ橋になりたいです。", vi: "Muốn làm cầu nối giữa …" },
                ],
                contextHintJp: "志望動機を論理的に説明します。",
                contextHintVi: "Trình bày lý do ứng tuyển một cách logic.",
            },
            {
                id: "q3",
                jp: "今まで一番印象に残ったプロジェクトを教えてください。",
                furigana: "いままでいちばんいんしょうにのこったプロジェクトをおしえてください。",
                vi: "Hãy nói về dự án bạn tâm đắc nhất.",
                vocab: [
                    { jp: "印象", furigana: "いんしょう", vi: "Ấn tượng" },
                    { jp: "プロジェクト", furigana: "プロジェクト", vi: "Dự án" },
                    { jp: "要件定義", furigana: "ようけんていぎ", vi: "Định nghĩa yêu cầu" },
                ],
                sentences: [
                    { jp: "〜のプロジェクトで、BrSEとして〜から関わりました。", vi: "Tham gia dự án … với vai trò …" },
                    { jp: "最も印象に残ったのは〜です。", vi: "Ấn tượng nhất là …" },
                ],
                contextHintJp: "経験したプロジェクトを具体的に説明します。",
                contextHintVi: "Mô tả cụ thể dự án từng tham gia.",
            },
            {
                id: "q4",
                jp: "あなたの強みは何ですか？",
                furigana: "あなたのつよみはなんですか？",
                vi: "Điểm mạnh của bạn là gì?",
                vocab: [
                    { jp: "強み", furigana: "つよみ", vi: "Điểm mạnh" },
                    { jp: "責任感", furigana: "せきにんかん", vi: "Tinh thần trách nhiệm" },
                    { jp: "コミュニケーション", furigana: "コミュニケーション", vi: "Giao tiếp" },
                ],
                sentences: [
                    { jp: "私の強みは〜と〜です。", vi: "Điểm mạnh của tôi là … và …" },
                    { jp: "〜を活かして貢献できます。", vi: "Có thể đóng góp bằng …" },
                ],
                contextHintJp: "自分の強みを具体例とともに伝えます。",
                contextHintVi: "Trình bày điểm mạnh kèm ví dụ cụ thể.",
            },
            {
                id: "q5",
                jp: "何か質問はありますか？",
                furigana: "なにかしつもんはありますか？",
                vi: "Bạn có câu hỏi nào không?",
                vocab: [
                    { jp: "御社", furigana: "おんしゃ", vi: "Quý công ty" },
                    { jp: "新人研修", furigana: "しんじんけんしゅう", vi: "Đào tạo nhân viên mới" },
                    { jp: "詳しく", furigana: "くわしく", vi: "Chi tiết" },
                ],
                sentences: [
                    { jp: "〜について、もう少し詳しく教えていただけますか？", vi: "Xin được nghe chi tiết hơn về …" },
                    { jp: "御社の〜はどのような〜ですか？", vi: "Công ty có chế độ … thế nào?" },
                ],
                contextHintJp: "面接の最後に逆質問をします。",
                contextHintVi: "Đặt câu hỏi ngược lại ở cuối buổi phỏng vấn.",
            },
            {
                id: "q6",
                jp: "希望の給料を教えてください。",
                furigana: "きぼうのきゅうりょうをおしえてください。",
                vi: "Mức lương mong muốn.",
                vocab: [
                    { jp: "希望", furigana: "きぼう", vi: "Mong muốn" },
                    { jp: "給料", furigana: "きゅうりょう", vi: "Lương" },
                    { jp: "規定", furigana: "きてい", vi: "Quy định" },
                ],
                sentences: [
                    { jp: "御社の規定に従いたいと考えております。", vi: "Theo quy định của công ty." },
                    { jp: "目安としては〇〇を希望しております。", vi: "Mức tham khảo là …" },
                ],
                contextHintJp: "希望給与を控えめに伝えます。",
                contextHintVi: "Trình bày mức lương mong muốn một cách khéo léo.",
            },
        ],
    },
];
